apiVersion: v1
kind: Service
metadata:
  name: nodejs-mongo-app-service
  labels:
    app: nodejs-frontend
spec:
  type: LoadBalancer
  selector:
    app: nodejs-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

